apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  namespace: bggns
  labels:
    app: bgg
    name: bggapp-svc
spec:
  type: ClusterIP
  # type: NodePort
  # type: LoadBalancer
  selector:
    app: bgg
    name: bggapp-po
  ports:
  - port: 3000
    targetPort: bggapp-port

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bggapp-ing
  namespace: bggns
  labels:
    app: bggns
    name: bggapp-ing
spec:
  ingressClassName: nginx
  rules:
  - host: bgg-137.184.249.161.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bggapp-svc
            port: 
              number: 3000
